import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { paymentVoucherSchema } from "@/lib/validations/paymentVoucher";

// GET - List all payment vouchers with optional filtering
export async function GET(request: Request) {
    const supabase = await createClient();
    const { searchParams } = new URL(request.url);

    const tourId = searchParams.get("tour_id");
    const status = searchParams.get("status");
    const payeeType = searchParams.get("payee_type");
    const limit = parseInt(searchParams.get("limit") || "50");
    const offset = parseInt(searchParams.get("offset") || "0");

    let query = supabase
        .from("payment_vouchers")
        .select("*")
        .order("created_at", { ascending: false })
        .range(offset, offset + limit - 1);

    if (tourId) {
        query = query.eq("tour_id", tourId);
    }
    if (status) {
        query = query.eq("status", status);
    }
    if (payeeType) {
        query = query.eq("payee_type", payeeType);
    }

    const { data: vouchers, error, count } = await query;

    if (error) {
        console.error("Error fetching payment vouchers:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ vouchers, count });
}

// POST - Create a new payment voucher
export async function POST(request: Request) {
    const supabase = await createClient();

    try {
        const body = await request.json();

        // Validate input
        const validatedData = paymentVoucherSchema.parse(body);

        // Get current user
        const { data: { user } } = await supabase.auth.getUser();

        // Create voucher (voucher_no is auto-generated by trigger)
        const { data: voucher, error } = await supabase
            .from("payment_vouchers")
            .insert({
                ...validatedData,
                created_by: user?.id,
            })
            .select()
            .single();

        if (error) {
            console.error("Error creating payment voucher:", error);
            return NextResponse.json({ error: error.message }, { status: 500 });
        }

        return NextResponse.json({ success: true, voucher }, { status: 201 });
    } catch (err: any) {
        console.error("Server error:", err);
        if (err.name === "ZodError") {
            return NextResponse.json(
                { error: "Validation error", details: err.errors },
                { status: 400 }
            );
        }
        return NextResponse.json(
            { error: "Internal server error" },
            { status: 500 }
        );
    }
}

// PUT - Update a payment voucher
export async function PUT(request: Request) {
    const supabase = await createClient();

    try {
        const body = await request.json();
        const { id, ...updateData } = body;

        if (!id) {
            return NextResponse.json(
                { error: "Voucher ID is required" },
                { status: 400 }
            );
        }

        // Validate input (partial update)
        const validatedData = paymentVoucherSchema.partial().parse(updateData);

        const { data: voucher, error } = await supabase
            .from("payment_vouchers")
            .update(validatedData)
            .eq("id", id)
            .select()
            .single();

        if (error) {
            console.error("Error updating payment voucher:", error);
            return NextResponse.json({ error: error.message }, { status: 500 });
        }

        return NextResponse.json({ success: true, voucher });
    } catch (err: any) {
        console.error("Server error:", err);
        if (err.name === "ZodError") {
            return NextResponse.json(
                { error: "Validation error", details: err.errors },
                { status: 400 }
            );
        }
        return NextResponse.json(
            { error: "Internal server error" },
            { status: 500 }
        );
    }
}

// DELETE - Delete a payment voucher
export async function DELETE(request: Request) {
    const supabase = await createClient();
    const { searchParams } = new URL(request.url);
    const id = searchParams.get("id");

    if (!id) {
        return NextResponse.json(
            { error: "Voucher ID is required" },
            { status: 400 }
        );
    }

    const { error } = await supabase
        .from("payment_vouchers")
        .delete()
        .eq("id", id);

    if (error) {
        console.error("Error deleting payment voucher:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true });
}
